thuong/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello_world', 'HelloWorldController@show');

Route::resource('users', 'UserController');

thuong/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use DB;
use Hash;

class User extends Authenticatable
{
    use SoftDeletes;    
    use Notifiable;

    protected $table = 'users';
    
    /**
     * The attributes that are mupdates the time.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'mail_address',
        'password',
        'name',
        'address',
        'phone',

    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Create new user in table Users 
     *
     * @param array $data
     * @return 
     */
    public function createUser(array $data)
    {
        $data['password'] = Hash::make($data['password']);
        return User::create($data);

    }

    /**
     * 
     */
    public function getUser(array $data)
    {
        $builder = User::orderBy('mail_address', 'ASC');

        if (isset($data['mail_address']) && $data['mail_address'] != '') {
            $builder->where('mail_address', 'LIKE', '%' . $data['mail_address'] . '%');
        }

        if (isset($data['name']) && $data['name'] != '') {
            $builder->where('name', 'LIKE', '%' . $data['name'] . '%');
        }

        if (isset($data['address']) && $data['address'] != '') {
            $builder->where('address', 'LIKE', '%' . $data['address'] . '%');
        }

        if (isset($data['phone']) && $data['phone'] != '') {
            $builder->where('phone', $data['phone']);
        }

        return $builder->paginate(20);

    }
}

thuong/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

thuong/app/Http/Controllers/HelloWorldController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HelloWorldController extends Controller
{
    public function show() {
        return view('show');
    }
}

thuong/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CreateUserRequest;
use App\Models\User;
use Helper;

class UserController extends Controller
{
    /**
     * The user implementation.
     *
     * @var User
     */
    protected $user;

    /**
     * Create a new controller instance.
     *
     * @param User $users
     * @return void
     */
    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * Show all users, return view a list of users
     *
     * @param 
     * @return view users.index
     */
    public function index(Request $request) 
    {
        $data = $request->all();
        $users = $this->user->getUser($data);
        return view('users.index', ['users' => $users]);
    }

    /**
     * Redirect to view create an user
     *
     * @param 
     * @return view users.create
     */
    public function create() 
    {
    	return view('users.create');
    }

    /**
     * Store user from request and 
     *
     * @param Request $request
     * @return view users.index
     */
    public function store(CreateUserRequest $request)
    {
        $data = $request->all();
        $this->user->createUser($data);
        flash(__('message.add_user_successfully'))->success();
        return redirect()->route('users.index');
    }
}

thuong/resources/views/layouts/default.blade.php
<html>
    @include('layouts.head')
    <body>
        <div class="container">
            @include('layouts.header')
            @yield('content')
        </div>

        @include('layouts.footer')
    </body>
</html>

thuong/resources/views/layouts/footer.blade.php
<div class="panel panel-default">
    <div class="panel-body text-center"> PHP training by LIFETIME technologies </div>
</div>

thuong/resources/views/layouts/head.blade.php
<head>
    <title>@yield('title')</title>
    {{-- css and js --}}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

thuong/resources/views/layouts/header.blade.php
@section('header')
    <h1> @yield('title') </h1>
@show

thuong/resources/views/show.blade.php
<h1>Hello World</h1>

thuong/resources/views/users/create.blade.php
@extends('layouts.default')

@section('title', 'Thêm mới người dùng')

@section('header')
    <div class="row">
        @parent
        <p> Đây là trang đăng ký người dùng </p> 
    </div>
@endsection

@section('content')
<div class="row">
    <div class="col-md-6">
        <form action="{{ route('users.store')}}" method="post" id="fileForm" role="form">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <fieldset><legend class="text-center">Nhập thông tin để đăng ký bắt buộc *</small></span></legend>
        <div class="form-group @if($errors->has('mail_address')) alert alert-danger @endif">
            <label for="email"><span class="req">* </span> Địa chỉ email: </label> 
                <input class="form-control" type="text" name="mail_address" id = "email" />  
            @if($errors->has('mail_address'))
                {{ $errors->first('mail_address') }}
            @endif
        </div>

        <div class="form-group {{ $errors->has('password') ? 'alert alert-danger' : '' }}">
            <label for="password"><span class="req">* </span> Mật khẩu: </label>
                <input name="password" type="password" class="form-control" id="pass1" /> </p>
            @if($errors->has('password'))
                {{ $errors->first('password') }}
            @endif
        </div>

        <div class="form-group @if($errors->has('password_confirmation')) {{'alert alert-danger'}} @endif">
            <label for="password"><span class="req">* </span> Mật khẩu xác nhận: </label>
                <input name="password_confirmation" type="password" class="form-control"/>
                    <span id="confirmMessage" class="confirmMessage"></span>
                @if($errors->has('password_confirmation'))
                    {{ $errors->first('password_confirmation') }}
                @endif
        </div>

        <div class="form-group @if($errors->has('name')) {{'alert alert-danger'}} @endif">     
            <label for="name"><span class="req">* </span> Tên: </label>
                <input class="form-control" type="text" name="name" id = "txt"/> 
            @if($errors->has('name'))
                {{ $errors->first('name') }}
            @endif
        </div>

        <div class="form-group @if($errors->has('address')) {{'alert alert-danger'}} @endif">
            <label for="address"><span class="req">* </span> Địa chỉ: </label> 
                <input class="form-control" type="text" name="address" id = "txt"  placeholder="" />
            @if($errors->has('address'))
                {{ $errors->first('address') }}
            @endif  
        </div>

        <div class="form-group @if($errors->has('phone')) {{'alert alert-danger'}} @endif">     
            <label for="phone"><span class="req">* </span> Số điện thoại: </label>
                <input class="form-control" type="text" name="phone" id = "txt" /> 
            @if($errors->has('phone'))
                {{ $errors->first('phone') }}
            @endif
        </div>

        <div class="form-group">
            <input class="btn btn-success" type="submit" name="submit_reg" value="Đăng ký">
        </div>
        </fieldset>     
        </form><!-- ends register form -->
    </div><!-- ends col-6 -->            
</div>
@endsection

thuong/resources/views/users/index.blade.php
@extends('layouts.default')
@section('title', 'Danh sách người dùng')

@section('header')
    <div class="row">
    @parent
        <p> Đây là trang danh sách người dùng </p> 
    </div>
@endsection

@section('content')
    <div class="row">
        <h2>Tìm kiếm người dùng</h2>
        <form method="get" action="{{ route('users.index') }}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="form-group">
                <label>Địa chỉ email</label>
                <input type="mail_address" class="form-control" name="mail_address" placeholder="Nhập địa chỉ email">
            </div>
            <div class="form-group">
                <label>Tên</label>
                <input type="name" class="form-control" name="name" placeholder="Nhập tên">
            </div>
            <div class="form-group">
                <label>Địa chỉ</label>
                <input type="address" class="form-control" name="address" placeholder="Nhập địa chỉ">
            </div>
            <div class="form-group">
                <label>Số điện thoại</label>
                <input type="phone" class="form-control" name="phone" placeholder="Nhập số điện thoại">
            </div>
            <div class="form-group">
                <input class="btn btn-info" type="submit" name="submit" value="Tìm kiếm">
            </div>
        </form>
    </div>
    <div class="row">
        <h2>Danh sách người sử dụng</h2>  
        <a href=" {{ route('users.create') }}" class="btn btn-info"> Đăng kí </a>   
        @include('flash::message')
            <div class="table-responsive">   
            <table class="table">
                <thead>
                    <tr>
                    <th class="text-center">Số thứ tự</th>
                    <th class="text-center">Địa chỉ email</th>
                    <th class="text-center">Tên</th>
                    <th class="text-center">Địa chỉ</th>
                    <th class="text-center">Số điện thoại</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr>
                    <td class="text-left">{{ (($users->currentPage() - 1 ) * $users->perPage() ) + $loop->iteration }}</td>
                    <td class="text-left">{{ $user->mail_address }}</td>
                    <td class="text-left">{{ Helper::toUpperCase($user->name) }}</td>
                    <td class="text-left">{{ $user->address }}</td>
                    <td class="text-left">{{ $user->phone }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $users->links() }}
        </div>
    </div>
@endsection
        